name: feed
favicon: null
layout_spectrum: 0.17805
typography_spectrum: 0.31536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#adadaf'
    - '#767c88'
    - '#5f3a1d'
    - '#8b0000'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
